namespace Modules.SusiCommon;

public static class SusiStatus
{
  public const UInt32 SUSI_STATUS_NOT_INITIALIZED = 0xFFFFFFFF;
  public const UInt32 SUSI_STATUS_INITIALIZED = 0xFFFFFFFE;
  public const UInt32 SUSI_STATUS_ALLOC_ERROR = 0xFFFFFFFD;
  public const UInt32 SUSI_STATUS_DRIVER_TIMEOUT = 0xFFFFFFFC;
  public const UInt32 SUSI_STATUS_INVALID_PARAMETER = 0xFFFFFEFF;
  public const UInt32 SUSI_STATUS_INVALID_BLOCK_ALIGNMENT = 0xFFFFFEFE;
  public const UInt32 SUSI_STATUS_INVALID_BLOCK_LENGTH = 0xFFFFFEFD;
  public const UInt32 SUSI_STATUS_INVALID_DIRECTION = 0xFFFFFEFC;
  public const UInt32 SUSI_STATUS_INVALID_BITMASK = 0xFFFFFEFB;
  public const UInt32 SUSI_STATUS_RUNNING = 0xFFFFFEFA;
  public const UInt32 SUSI_STATUS_UNSUPPORTED = 0xFFFFFCFF;
  public const UInt32 SUSI_STATUS_NOT_FOUND = 0xFFFFFBFF;
  public const UInt32 SUSI_STATUS_TIMEOUT = 0xFFFFFBFE;
  public const UInt32 SUSI_STATUS_BUSY_COLLISION = 0xFFFFFBFD;
  public const UInt32 SUSI_STATUS_READ_ERROR = 0xFFFFFAFF;
  public const UInt32 SUSI_STATUS_WRITE_ERROR = 0xFFFFFAFE;
  public const UInt32 SUSI_STATUS_MORE_DATA = 0xFFFFF9FF;
  public const UInt32 SUSI_STATUS_ERROR = 0xFFFFF0FF;
  public const UInt32 SUSI_STATUS_SUCCESS = 0x00000000;
}