//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.TestProcess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.TestProcess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying sensor values in Ready state.
        /// </summary>
        internal static string _detailsMessage {
            get {
                return ResourceManager.GetString("_detailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablation Tests.
        /// </summary>
        internal static string AblationTestsText {
            get {
                return ResourceManager.GetString("AblationTestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible Test.
        /// </summary>
        internal static string AudibleTestText {
            get {
                return ResourceManager.GetString("AudibleTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS Tests.
        /// </summary>
        internal static string DMSTestText {
            get {
                return ResourceManager.GetString("DMSTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETS Tests.
        /// </summary>
        internal static string ETSTestText {
            get {
                return ResourceManager.GetString("ETSTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle State.
        /// </summary>
        internal static string IdleStateText {
            get {
                return ResourceManager.GetString("IdleStateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Test.
        /// </summary>
        internal static string InputTestText {
            get {
                return ResourceManager.GetString("InputTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Tests.
        /// </summary>
        internal static string ManualTestsText {
            get {
                return ResourceManager.GetString("ManualTestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPS Tests.
        /// </summary>
        internal static string OPSTestText {
            get {
                return ResourceManager.GetString("OPSTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Check.
        /// </summary>
        internal static string ParameterCheckText {
            get {
                return ResourceManager.GetString("ParameterCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Test.
        /// </summary>
        internal static string PerformanceTestText {
            get {
                return ResourceManager.GetString("PerformanceTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRESS.
        /// </summary>
        internal static string ProgressText {
            get {
                return ResourceManager.GetString("ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready State.
        /// </summary>
        internal static string ReadyStateText {
            get {
                return ResourceManager.GetString("ReadyStateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test:.
        /// </summary>
        internal static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        internal static string Step1Text {
            get {
                return ResourceManager.GetString("Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        internal static string Step2Text {
            get {
                return ResourceManager.GetString("Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        internal static string Step3Text {
            get {
                return ResourceManager.GetString("Step3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE:.
        /// </summary>
        internal static string SystemStateTitle {
            get {
                return ResourceManager.GetString("SystemStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST DETAILS:.
        /// </summary>
        internal static string TestDetailsTitleText {
            get {
                return ResourceManager.GetString("TestDetailsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string TestsText {
            get {
                return ResourceManager.GetString("TestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Verification.
        /// </summary>
        internal static string VersionVerificationText {
            get {
                return ResourceManager.GetString("VersionVerificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Test.
        /// </summary>
        internal static string VisualTestText {
            get {
                return ResourceManager.GetString("VisualTestText", resourceCulture);
            }
        }
    }
}
