<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IntermediateOutputPath>$(SolutionDir)\Build\Intermediate\</IntermediateOutputPath>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>false</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>$(SolutionDir)\Build\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="System.Management" Version="10.0.7" />
  </ItemGroup>

</Project>
