//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ablation
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public string Description { get; set; }
        public int AblationNumber { get; set; }
        public Nullable<int> AblationDuration { get; set; }
        public string DataFile { get; set; }
        public string TreatmentNote { get; set; }
        public int ProcedureId { get; set; }
        public string ErrorInformation { get; set; }
    
        public virtual Procedure Procedure { get; set; }
    }
}
