//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AblationData
    {
        public int ID { get; set; }
        public double TC1Reading { get; set; }
        public int TimeInSecondIndex { get; set; }
        public int AblationID { get; set; }
    }
}
