//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalloonParameters
    {
        public int Id { get; set; }
        public Nullable<double> LowPressureSetpoint { get; set; }
        public Nullable<double> HighPressureSetPoint { get; set; }
        public Nullable<double> LowFlowSetPoint { get; set; }
        public Nullable<double> HighFlowSetPoint { get; set; }
        public Nullable<double> RampUpTimeByStep { get; set; }
        public Nullable<double> PressureRampUpValue { get; set; }
        public Nullable<double> RampDownTimeByStep { get; set; }
        public Nullable<double> PressureRampDownValue { get; set; }
        public Nullable<double> TotalRampUpTime { get; set; }
        public Nullable<double> TotalRampDowntime { get; set; }
        public int StateID { get; set; }
        public double LowTargetInjectionPressure { get; set; }
        public double HighTargetInjectionPressure { get; set; }
        public double DASLowFlow { get; set; }
    }
}
