//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatheterType
    {
        public CatheterType()
        {
            this.CatheterInformations = new HashSet<CatheterInformation>();
            this.CMCRegisterValues = new HashSet<CMCRegisterValue>();
            this.PMCRegisterValues = new HashSet<PMCRegisterValue>();
        }
    
        public int ID { get; set; }
        public int CatheterID { get; set; }
        public string Description { get; set; }
        public string EngineeringDescription { get; set; }
    
        public virtual ICollection<CatheterInformation> CatheterInformations { get; set; }
        public virtual ICollection<CMCRegisterValue> CMCRegisterValues { get; set; }
        public virtual ICollection<PMCRegisterValue> PMCRegisterValues { get; set; }
    }
}
