//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatheterInformation
    {
        public int ID { get; set; }
        public int SerialNumber { get; set; }
        public int FirmwareVersion { get; set; }
        public System.DateTime CatheterExpirationDate { get; set; }
        public System.DateTime LastUseDate { get; set; }
        public int NumberOfInjection { get; set; }
        public int Lot { get; set; }
        public bool IsUsedForEngineering { get; set; }
        public int OverloadedCatheterID { get; set; }
        public int CatheterTypeID { get; set; }
    
        public virtual CatheterType CatheterType { get; set; }
    }
}
