//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMCRegisterValue
    {
        public int ID { get; set; }
        public int StateID { get; set; }
        public double PT1TankPressureLow { get; set; }
        public double PT1PressureThresholdHighLimit { get; set; }
        public double PT1TankPressureTooHigh { get; set; }
        public double PT1PressureLowRangeLimit { get; set; }
        public double PT1PressureHighRangeLimit { get; set; }
        public double PT2PressureThresholdHighLimit { get; set; }
        public double PT2PressureLowRangeLimit { get; set; }
        public double PT2PressureHighRangeLimit { get; set; }
        public double PT3PressureThresholdHighLimit { get; set; }
        public double PT3PressureLowRangeLimit { get; set; }
        public double PT3PressureHighRangeLimit { get; set; }
        public double PT4PressureThresholdHighLimit { get; set; }
        public double PT4PressureLowRangeLimit { get; set; }
        public double PT4PressureHighRangeLimit { get; set; }
        public double TS1TemperatureThresholdHighLimit { get; set; }
        public double TS1TemperatureLowRangeLimit { get; set; }
        public double TS1TemperatureHighRangeLimit { get; set; }
        public double FM1FlowMeterThresholLowlimit { get; set; }
        public double FM1FlowMeterThresholHighlimit { get; set; }
        public double FM1FlowMeterLowRangeLimit { get; set; }
        public double FM1FlowMeterHighRangelimit { get; set; }
        public double PS1PressureThresholdHighLimit { get; set; }
        public double PS1PressureLowRangeLimit { get; set; }
        public double PS1PressureHighRangeLimit { get; set; }
        public double PS2PressureThresholdHighLimit { get; set; }
        public double PS2PressureLowRangeLimit { get; set; }
        public double PS2PressureHighRangeLimit { get; set; }
        public double LC1LoadCellThresholdWarning { get; set; }
        public double LC1LoadCellThresholdFail { get; set; }
        public double LC1LoadCellLowRangeLimit { get; set; }
        public double LC1LoadCellHighRangeLimit { get; set; }
        public double PGain { get; set; }
        public double IGain { get; set; }
        public double DGain { get; set; }
        public double Offset { get; set; }
        public int CatheterTypeID { get; set; }
        public double TargetInjectionFlow { get; set; }
        public double TargetInjectionPressure { get; set; }
        public double LowFlow { get; set; }
    
        public virtual CatheterType CatheterType { get; set; }
    }
}
