//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMCUPIDLogs
    {
        public int Id { get; set; }
        public double FM1 { get; set; }
        public double PT2 { get; set; }
        public double TargetFlow { get; set; }
        public double TargetInjectionPressure { get; set; }
        public double TargetFlowError { get; set; }
        public double TargetInjectionPressureError { get; set; }
        public double P { get; set; }
        public double I { get; set; }
        public double D { get; set; }
        public double O { get; set; }
        public System.DateTime DateOfChange { get; set; }
    }
}
