//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Console
    {
        public Console()
        {
            this.Tanks = new HashSet<Tank>();
        }
    
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public bool IsReleased { get; set; }
        public int Efficiency { get; set; }
        public long UtilisationDuration { get; set; }
        public Nullable<int> CurrentTank { get; set; }
        public bool IsUsingPurge { get; set; }
        public bool IsUsingCatheterDeflateSwitch { get; set; }
        public bool IsBalloonRampDownActivated { get; set; }
        public bool IsUsingDeflateAfterThaw { get; set; }
        public bool IsUsingBloodPressureSensor { get; set; }
        public string ComPortName { get; set; }
        public bool IsUsingLowFlow { get; set; }
        public bool IsUsingDaylightSavingTime { get; set; }
    
        public virtual ICollection<Tank> Tanks { get; set; }
        public virtual HardDrive HardDrive { get; set; }
    }
}
