//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsoleVersion
    {
        public ConsoleVersion()
        {
            this.ErrorLogs = new HashSet<ErrorLog>();
        }
    
        public int Id { get; set; }
        public string Software { get; set; }
        public string ControlFirmware { get; set; }
        public string ControlFirmwareBootLoader { get; set; }
        public string CPLDFirmware { get; set; }
        public string RemoteFirmware { get; set; }
        public string RemoteFirmwareBootLoader { get; set; }
        public string PatientFirmware { get; set; }
        public string PatientFirmwareBootLoader { get; set; }
        public string RepeaterFirmware { get; set; }
        public string RepeaterFirmwareBootLoader { get; set; }
        public string ICBFirmware { get; set; }
        public string ICBFirmwareBootLoader { get; set; }
        public string CatheterFirmware { get; set; }
        public string DataBaseVersion { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual ICollection<ErrorLog> ErrorLogs { get; set; }
    }
}
