//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAccessContainer : DbContext
    {
        public DataAccessContainer()
            : base("name=DataAccessContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Physician> Physicians { get; set; }
        public DbSet<Ablation> Ablations { get; set; }
        public DbSet<AblationData> AblationDatas { get; set; }
        public DbSet<Console> Consoles { get; set; }
        public DbSet<CatheterType> CatheterTypes { get; set; }
        public DbSet<SystemState> SystemStates { get; set; }
        public DbSet<CMCRegisterValue> CMCRegisterValues { get; set; }
        public DbSet<PMCRegisterValue> PMCRegisterValues { get; set; }
        public DbSet<CatheterInformation> CatheterInformations { get; set; }
        public DbSet<Procedure> Procedures { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<UserAction> UserActions { get; set; }
        public DbSet<Action> Actions { get; set; }
        public DbSet<CMCUPIDLogs> CMCUPIDLogs { get; set; }
        public DbSet<PMCUPIDLogs> PMCUPIDLogs { get; set; }
        public DbSet<Tank> Tanks { get; set; }
        public DbSet<preference> preferences { get; set; }
        public DbSet<DataBaseVersion> DataBaseVersions { get; set; }
        public DbSet<FailuresLogs> FailuresLogs { get; set; }
        public DbSet<Settings> Settings { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<GUIField> GUIFields { get; set; }
        public DbSet<Translation> Translations { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<ErrorType> ErrorTypes { get; set; }
        public DbSet<ErrorMessage> ErrorMessages { get; set; }
        public DbSet<BalloonParameters> BalloonParameters { get; set; }
        public DbSet<TankTypes> TankTypes { get; set; }
        public DbSet<ProcedureLog> ProcedureLogs { get; set; }
        public DbSet<HardDrive> HardDrives { get; set; }
        public DbSet<ConsoleVersion> ConsoleVersions { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<HospitalInformation> HospitalInformations { get; set; }
    }
}
