//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public string ErrorInformation { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public long ErrorCode { get; set; }
        public int ErrorType { get; set; }
        public int VersionId { get; set; }
        public Nullable<int> CatheterID { get; set; }
        public int SystemStatesID { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool IsUsingICB { get; set; }
        public bool IsUsingRemote { get; set; }
        public string CatheterContainer { get; set; }
    
        public virtual ConsoleVersion ConsoleVersion { get; set; }
    }
}
