//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardDrive
    {
        public HardDrive()
        {
            this.WarningLimit = 500;
            this.FailLimit = 100;
        }
    
        public int Id { get; set; }
        public long WarningLimit { get; set; }
        public long FailLimit { get; set; }
    
        public virtual Console Console { get; set; }
    }
}
