//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class Patient
    {
        public Patient()
        {
            this.Procedures = new HashSet<Procedure>();
        }

        public Patient(Patient previousPatient)
        {
            FirstName = previousPatient.FirstName;
            LastName = previousPatient.LastName;
            Weight = previousPatient.Weight;
            Height = previousPatient.Height;
            Gender = previousPatient.Gender;
            DateOfBirth = previousPatient.DateOfBirth;

        }

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public short Gender { get; set; }
        public System.DateTime TreatmentDateTime { get; set; }
        public string HospitalPatientId { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public int PhysicianID { get; set; }
        public byte[] DateOfBirthEncrypted { get; set; }
        public byte[] WeightEncrypted { get; set; }
        public byte[] FirstNameEncrypted { get; set; }
        public byte[] LastNameEncrypted { get; set; }
        public byte[] GenderEncrypted { get; set; }
        public byte[] HeightEncrypted { get; set; }

        public virtual Physician Physician { get; set; }
        public virtual ICollection<Procedure> Procedures { get; set; }
    }
}
