//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMCRegisterValue
    {
        public int ID { get; set; }
        public int StateID { get; set; }
        public double CP1PressureThresholdHighLimit { get; set; }
        public double CP1PressureLowRangeLimit { get; set; }
        public double CP1PressureHighRangeLimit { get; set; }
        public double CP2PressureThresholdHighLimit { get; set; }
        public double CP2PressureLowRangeLimit { get; set; }
        public double CP2PressureHighRangeLimit { get; set; }
        public double TC1ThawingTemperature { get; set; }
        public double Pgain { get; set; }
        public double Igain { get; set; }
        public double Dgain { get; set; }
        public double Offset { get; set; }
        public double TargetBalloonPressure { get; set; }
        public short LowerBloodThreshold { get; set; }
        public short UpperBloodThreshold { get; set; }
        public int CatheterTypeID { get; set; }
        public double ThawingTemperatureSetPoint { get; set; }
    
        public virtual CatheterType CatheterType { get; set; }
    }
}
