//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMCUPIDLogs
    {
        public int Id { get; set; }
        public double PT3 { get; set; }
        public double IBP { get; set; }
        public double OBP { get; set; }
        public double PWMINJ { get; set; }
        public double PWMBAL { get; set; }
        public double TargetBalloonPressure { get; set; }
        public double TargetBallonPressureError { get; set; }
        public double P { get; set; }
        public double I { get; set; }
        public double D { get; set; }
        public double O { get; set; }
        public System.DateTime DateOfChange { get; set; }
    }
}
