//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class preference
    {
        public preference()
        {
            this.AblationDurationType = 1;
        }
    
        public int Id { get; set; }
        public double CoolingRequiredTargetTemperature { get; set; }
        public double ThawTimerToTemperature { get; set; }
        public double LowAblationTemperatureAlarm { get; set; }
        public double HighAblationTemperatureAlarm { get; set; }
        public double EsophagusTemperature { get; set; }
        public double DiaphragmAmplitude { get; set; }
        public int DiaphragmAmplitudeType { get; set; }
        public bool BalloonPressureSelected { get; set; }
        public bool TipPressureSelected { get; set; }
        public int AblationTimer { get; set; }
        public bool IsUsingAutoDeflation { get; set; }
        public short VolumeLevel { get; set; }
        public short CurveStyle { get; set; }
        public short CurveColor { get; set; }
        public string Background { get; set; }
        public bool IsUsingInflationFastSpeed { get; set; }
        public short RefrigerantLevelUnit { get; set; }
        public short DiaphragmSensorGain { get; set; }
        public bool IgnoreDiaphragmMovement { get; set; }
        public double DMSDetectionThreshold { get; set; }
        public bool IgnoreEsophagusTemperatureMonitoring { get; set; }
        public int VeinIsolationDuration { get; set; }
        public int RequestedAblationTime { get; set; }
        public int NewVeinIsolationDuration { get; set; }
        public int NewRequestedAblationTime { get; set; }
        public int ExpectedVeinIsolationTime { get; set; }
        public int AblationTimerTTIFixed { get; set; }
        public int NewAblationTimerTTIFixed { get; set; }
        public int DurationExpectedVeinIsolationTime { get; set; }
        public int AblationTimerTTI { get; set; }
        public int NewAblationTimerTTI { get; set; }
        public bool IsUsingAudioAlert { get; set; }
        public short AblationDurationType { get; set; }
        public bool EnabaleEnhancedAudio { get; set; }
        public bool IsUsingAutoPlayback { get; set; }
        public int OcclusionPressureGraphSweepSpeed { get; set; }
        public int OcclusionPressureGraphAxisYMaximum { get; set; }
        public int OcclusionPressureGraphAxisYMinimum { get; set; }
        public bool IsShowPatientInfo { get; set; }
        public bool IsShowAdvancedView { get; set; }
        public bool IsUsingShadowing { get; set; }
    
        public virtual Physician Physician { get; set; }
    }
}
