//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureLog
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime LogDate { get; set; }
        public string PreviousInformation { get; set; }
        public string CommittedInformation { get; set; }
        public int ProcedureId { get; set; }
    
        public virtual Procedure Procedure { get; set; }
    }
}
