//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure
    {
        public Procedure()
        {
            this.Archived = false;
            this.Ablations = new HashSet<Ablation>();
            this.ProcedureLogs = new HashSet<ProcedureLog>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime ProcedureStartDateTime { get; set; }
        public int PhysicianID { get; set; }
        public string Diagnosis { get; set; }
        public string OutCome { get; set; }
        public short SkinToSkinDuration { get; set; }
        public bool IsDataEdited { get; set; }
        public bool Archived { get; set; }
        public int ProcedureLogId { get; set; }
        public int PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<Ablation> Ablations { get; set; }
        public virtual ICollection<ProcedureLog> ProcedureLogs { get; set; }
    }
}
