//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int Id { get; set; }
        public int CurrentLanguage { get; set; }
        public bool AllowBluetooth { get; set; }
        public bool AllowLocalisation { get; set; }
        public bool AllowWifi { get; set; }
        public short WeightUnit { get; set; }
        public short ToiseUnit { get; set; }
        public int SelectedUserManualLanguage { get; set; }
        public double LoadCellCalibrationFactor { get; set; }
    }
}
