//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public double WeightAtReplacementDate { get; set; }
        public double WeightAtEndOfUseDate { get; set; }
        public System.DateTime ReplacementDate { get; set; }
        public System.DateTime EndOfUseDate { get; set; }
        public short TankTypesID { get; set; }
        public int ConsoleID { get; set; }
    
        public virtual Console Console { get; set; }
    }
}
