//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TankTypes
    {
        public int Id { get; set; }
        public double CylinderSize { get; set; }
        public double NetContent { get; set; }
        public double Pressure { get; set; }
        public short CGAConnection { get; set; }
        public double Height { get; set; }
        public double OutsideDiameter { get; set; }
        public double Weight { get; set; }
        public string Description { get; set; }
        public double MetalWeight { get; set; }
    }
}
