//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int Id { get; set; }
        public string FieldTranslation { get; set; }
        public int LanguageId { get; set; }
        public int GUIFieldId { get; set; }
    
        public virtual GUIField GUIField { get; set; }
    }
}
