//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Types = new HashSet<Type>();
            this.UserActions = new HashSet<UserAction>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string EmailAdredress { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Type> Types { get; set; }
        public virtual ICollection<UserAction> UserActions { get; set; }
    }
}
