<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IntermediateOutputPath>$(SolutionDir)\Build\Intermediate\</IntermediateOutputPath>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>$(SolutionDir)\Build\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="Prism.Unity" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Providers\SystemManagementProvider\SystemManagementProvider.csproj" />
    <ProjectReference Include="..\..\Shared\Converters\Converters.csproj" />
    <ProjectReference Include="..\..\Shared\SharedDefinitions\SharedDefinitions.csproj" />
    <ProjectReference Include="..\LogModule\LogModule.csproj" />
    <ProjectReference Include="..\ResourceModule\ResourceModule.csproj" />
  </ItemGroup>

</Project>
