<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IntermediateOutputPath>$(SolutionDir)\Build\Intermediate\</IntermediateOutputPath>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>$(SolutionDir)\Build\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.8" />
    <PackageReference Include="System.Management" Version="10.0.8" />
  </ItemGroup>

</Project>
