using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;

namespace WarningMessagesManager
{
    /// <summary>
    /// This class handles the warning messages list.
    /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
    /// </summary>
    public class WarningMessagesManager
    {

        public enum ErrorTypes
        {
            Unknown = 0,
            CMCU = 1,
            PMCU = 2,
            GUI = 3

        }

        private ObservableCollection<WarningMessage> warningMessagesList;

        /// <summary>
        /// Constructor that initializes the list of warning messages generated by the system.
        /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
        /// </summary>
        public WarningMessagesManager()
        {
            warningMessagesList = new ObservableCollection<WarningMessage>();
        }

        /// <summary>
        /// This read-only property handles the Warning Messages list.
        /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
        /// </summary>
        public ObservableCollection<WarningMessage> WarningMessagesList
        {
            get
            {
                return warningMessagesList;
            }
        }

        /// <summary>
        /// This method adds a string message to the warning messages list.
        /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
        /// </summary>
        /// <param name="message">The string message to add to the list.</param>
        public void AddMessage(List<Tuple<long, string, string, string>> errors, WarningMessagesManagerEnumeration.MessageType type = WarningMessagesManagerEnumeration.MessageType.SYSTEM, object errorTypes = null)
        {
            string errorType = string.Empty;

            if (errorTypes != null)
            {

                errorType = BoardTypeToString((ErrorTypes)errorTypes);

            }

            foreach (Tuple<long, string, string, string> error in errors)
            {
                warningMessagesList.Add(new WarningMessage(error.Item2, error.Item4, type, errorType));
            }
        }

        /// <summary>
        /// This method removes, if found, a string from the warning messages list.
        /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
        /// </summary>
        /// <param name="message">The string message to remove from the list.</param>
        public void RemoveMessage(string message)
        {
            WarningMessage warningMessage = new WarningMessage(message, string.Empty);

            if (warningMessagesList.Contains(warningMessage))
            {
                warningMessagesList.Remove(warningMessage);
            }
        }

        /// <summary>
        /// This methode searches for a message in the warning messages list.
        /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
        /// </summary>
        /// <param name="message">The string message to search.</param>
        /// <returns>If the message has been found.</returns>
        public bool SearchMessage(string message)
        {

            bool isMessageContained = false;


            List<string> _Message = new List<string>();

            int lenght = message.Length;

            try
            {
                if (message.Length > 0)
                {
                    if (message.Contains("Error"))
                    {
                        message = message.Replace("Error", "");
                    }

                    if (message.Contains("Warning"))
                    {
                        message = message.Replace("Warning", "");

                    }

                    if (message != string.Empty && message.Contains("-"))
                    {
                        _Message = new List<string>(message.Split('-'));

                        //if (_Message[2] == "Cable")
                        //{
                        //    _Message[1] = _Message[1] + "-" + _Message[2];
                        //    _Message[2] = "";
                        //}

                        _Message = _Message.FindAll(x => !string.IsNullOrEmpty(x) && x.Length >= 8);
                    }
                    else
                    {
                        try
                        {
                            if(_Message.Count != 0) // CAN create problem for the CAN2
                             _Message[0] = message;
                        }
                        catch (Exception ex)
                        {
                            ex.ToString();

                        }
                    }

                    foreach (string ConsoleElement in _Message)
                    {

                        isMessageContained = false;

                        foreach (WarningMessage element in warningMessagesList)
                        {
                            try
                            {
                                if (ConsoleElement.Contains(element.Message))
                                {
                                    isMessageContained = true;

                                }
                            }
                            catch (Exception ex)
                            {
                                ex.ToString();
                            }
                        }

                        if (!isMessageContained)
                        {
                            return false;
                        }

                    }
                }
            }

            catch (Exception ex)
            {
                ex.ToString(); //TODO
            }

            return isMessageContained;
        }

        /// <summary>
        /// This method clears the warning messages list.
        /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
        /// </summary>
        public void ClearList()
        {
            warningMessagesList.Clear();
        }

        /// <summary>
        /// This method returns a string of board type
        /// . Safety classification: No injury or damage to health is possible (IEC 62304 Class A).
        /// </summary>

        private string BoardTypeToString(ErrorTypes errorType = ErrorTypes.Unknown)
        {
            string boardType = string.Empty;

            switch (errorType)
            {
                case ErrorTypes.CMCU:

                    boardType = "-1";
                    break;
                case ErrorTypes.PMCU:
                    boardType = "-2";
                    break;
            }

            return boardType;
        }
    }

    public enum ErrorTypes
    {
        Unknown = 0,
        CMCU = 1,
        PMCU = 2,
        GUI = 3

    }

}