//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.SystemParameters.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.SystemParameters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string AccessoriesTitle {
            get {
                return ResourceManager.GetString("AccessoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_D_GAIN:.
        /// </summary>
        internal static string B_D_GainText {
            get {
                return ResourceManager.GetString("B_D_GainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_I_GAIN:.
        /// </summary>
        internal static string B_I_GainText {
            get {
                return ResourceManager.GetString("B_I_GainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_OFFSET:.
        /// </summary>
        internal static string B_OffsetText {
            get {
                return ResourceManager.GetString("B_OffsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_P_GAIN:.
        /// </summary>
        internal static string B_P_GainText {
            get {
                return ResourceManager.GetString("B_P_GainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootloader.
        /// </summary>
        internal static string BootloaderTitle {
            get {
                return ResourceManager.GetString("BootloaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control:.
        /// </summary>
        internal static string CMCUBooTVersionText {
            get {
                return ResourceManager.GetString("CMCUBooTVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control:.
        /// </summary>
        internal static string CMCUVersionText {
            get {
                return ResourceManager.GetString("CMCUVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPLD:.
        /// </summary>
        internal static string CPLDVersionText {
            get {
                return ResourceManager.GetString("CPLDVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database:.
        /// </summary>
        internal static string DBVersionText {
            get {
                return ResourceManager.GetString("DBVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        internal static string FirmwareTitle {
            get {
                return ResourceManager.GetString("FirmwareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM1:.
        /// </summary>
        internal static string FM1Text {
            get {
                return ResourceManager.GetString("FM1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        internal static string GraphsTitle {
            get {
                return ResourceManager.GetString("GraphsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI:.
        /// </summary>
        internal static string GUIVersionText {
            get {
                return ResourceManager.GetString("GUIVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_D_GAIN:.
        /// </summary>
        internal static string I_D_GainText {
            get {
                return ResourceManager.GetString("I_D_GainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_I_GAIN:.
        /// </summary>
        internal static string I_I_GainText {
            get {
                return ResourceManager.GetString("I_I_GainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_OFFSET:.
        /// </summary>
        internal static string I_OffsetText {
            get {
                return ResourceManager.GetString("I_OffsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_P_GAIN:.
        /// </summary>
        internal static string I_P_GainText {
            get {
                return ResourceManager.GetString("I_P_GainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBP:.
        /// </summary>
        internal static string IBPText {
            get {
                return ResourceManager.GetString("IBPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICB:.
        /// </summary>
        internal static string ICBBootVersionText {
            get {
                return ResourceManager.GetString("ICBBootVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICB:.
        /// </summary>
        internal static string ICBVersionText {
            get {
                return ResourceManager.GetString("ICBVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC1:.
        /// </summary>
        internal static string LCText {
            get {
                return ResourceManager.GetString("LCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM PARAMETERS.
        /// </summary>
        internal static string ModuleTitle {
            get {
                return ResourceManager.GetString("ModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBP:.
        /// </summary>
        internal static string OBPText {
            get {
                return ResourceManager.GetString("OBPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient:.
        /// </summary>
        internal static string PMCUBootVersionText {
            get {
                return ResourceManager.GetString("PMCUBootVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient:.
        /// </summary>
        internal static string PMCUVersionText {
            get {
                return ResourceManager.GetString("PMCUVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT1:.
        /// </summary>
        internal static string PT1Text {
            get {
                return ResourceManager.GetString("PT1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT2:.
        /// </summary>
        internal static string PT2Text {
            get {
                return ResourceManager.GetString("PT2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT3:.
        /// </summary>
        internal static string PT3Text {
            get {
                return ResourceManager.GetString("PT3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT4:.
        /// </summary>
        internal static string PT4Text {
            get {
                return ResourceManager.GetString("PT4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PT5:.
        /// </summary>
        internal static string PT5Text {
            get {
                return ResourceManager.GetString("PT5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM1:.
        /// </summary>
        internal static string PWM1Text {
            get {
                return ResourceManager.GetString("PWM1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM2:.
        /// </summary>
        internal static string PWM2Text {
            get {
                return ResourceManager.GetString("PWM2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote:.
        /// </summary>
        internal static string RCMCUBootText {
            get {
                return ResourceManager.GetString("RCMCUBootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote:.
        /// </summary>
        internal static string RCMCUVersionText {
            get {
                return ResourceManager.GetString("RCMCUVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeater:.
        /// </summary>
        internal static string RMCUBootVersionText {
            get {
                return ResourceManager.GetString("RMCUBootVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeater:.
        /// </summary>
        internal static string RMCUVersionText {
            get {
                return ResourceManager.GetString("RMCUVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        internal static string SensorsTitle {
            get {
                return ResourceManager.GetString("SensorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC1:.
        /// </summary>
        internal static string TemperatureText {
            get {
                return ResourceManager.GetString("TemperatureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS1:.
        /// </summary>
        internal static string TS1Text {
            get {
                return ResourceManager.GetString("TS1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string VersionsTitle {
            get {
                return ResourceManager.GetString("VersionsTitle", resourceCulture);
            }
        }
    }
}
